[theme]
base="light"
primaryColor="#297E91"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F4F8F9"
textColor="#1A4D5B"
font="sans serif"

[server]
fileWatcherType = "none"
maxUploadSize = 1000
maxMessageSize = 500
